import json
import threading
import time

import pytest

from mtplx.agent_workspace import WorkspaceConflictError, WorkspaceStore
from mtplx.graph_executor import GraphExecutionError, GraphExecutor
from mtplx.graphs import GraphStore
from mtplx.memory import MemoryStore
from mtplx.workspace_tools import WorkspaceToolService


def _wait_for(graph_store, run_id, predicate, *, timeout=10):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        run = graph_store.get_run(run_id)
        if predicate(run):
            return run
        time.sleep(0.01)
    run = graph_store.get_run(run_id)
    raise AssertionError(
        f"Graph run did not reach expected state: {run.status}, "
        f"node={run.current_node_id}, error={run.error}"
    )


def _stores(tmp_path, *, policy=None):
    project = tmp_path / "project"
    project.mkdir()
    workspace_store = WorkspaceStore(tmp_path / "state")
    workspace = workspace_store.create_workspace(
        "Graph project",
        str(project),
        model="mtplx-test-model",
        tool_policy=policy,
    )
    graph_store = GraphStore(workspace_store)
    tool_service = WorkspaceToolService(workspace_store, sandbox_mode="off")
    memory_store = MemoryStore(tmp_path / "memory")
    return project, workspace_store, workspace, graph_store, tool_service, memory_store


def _runtime_snapshot(**overrides):
    snapshot = {
        "provider": "mtplx",
        "runtime_loaded": True,
        "backend_id": "mtplx",
        "loaded_model": "mtplx-test-model",
        "runtime_capabilities": [],
        "memory_pressure_level": 0,
        "thermal_throttled": False,
        "active_memory_bytes": 0,
        "context_window": 1_048_576,
        "runtime_profile": "auto",
    }
    snapshot.update(overrides)
    return snapshot


def _full_graph(workspace_id):
    return {
        "schema_version": 1,
        "id": "coding-graph",
        "project_id": workspace_id,
        "workspace_id": workspace_id,
        "name": "Coding Graph",
        "limits": {
            "max_steps": 20,
            "max_context_tokens": 32768,
            "max_concurrency": 1,
        },
        "policies": {"write": "ask", "terminal": "ask", "memory": "ask"},
        "nodes": [
            {"id": "input", "type": "input"},
            {
                "id": "plan",
                "type": "model",
                "config": {"prompt": "Plan {{inputs.goal}}", "max_tokens": 128},
            },
            {
                "id": "repeat",
                "type": "loop",
                "config": {
                    "max_iterations": 2,
                    "body": {
                        "type": "model",
                        "config": {
                            "prompt": "Iteration {{loop.index}} after {{nodes.plan.output}}",
                            "max_tokens": 64,
                        },
                    },
                },
            },
            {
                "id": "write",
                "type": "tool",
                "config": {
                    "tool": "write_file",
                    "arguments": {
                        "path": "generated.txt",
                        "content": "generated by Graph\n",
                    },
                },
            },
            {
                "id": "test",
                "type": "tool",
                "config": {
                    "tool": "run_tests",
                    "arguments": {
                        "command": "test -f generated.txt",
                        "network": False,
                    },
                },
            },
            {
                "id": "gate",
                "type": "human_approval",
                "config": {
                    "action": "Accept verified Graph result",
                    "description": "Confirm the recorded write and test evidence.",
                    "payload": {"test": "{{nodes.test.output}}"},
                },
            },
            {
                "id": "output",
                "type": "output",
                "config": {
                    "mapping": {
                        "plan": "{{nodes.plan.output}}",
                        "iterations": "{{nodes.repeat.output}}",
                        "approved": "{{nodes.gate.output.approved}}",
                    }
                },
            },
        ],
        "edges": [
            {"source": "input", "target": "plan"},
            {"source": "plan", "target": "repeat"},
            {"source": "repeat", "target": "write"},
            {"source": "write", "target": "test"},
            {"source": "test", "target": "gate"},
            {"source": "gate", "target": "output"},
        ],
    }


def test_graph_runs_model_loop_tools_and_exact_approvals_to_recorded_completion(tmp_path):
    project, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    calls = []

    def model_runner(**kwargs):
        calls.append(dict(kwargs))
        node_id = kwargs["node_id"]
        prompt = kwargs["messages"][0]["content"]
        content = "I am done" if node_id == "plan" else f"{node_id}: {prompt}"
        return {
            "model": kwargs["model"],
            "choices": [{"message": {"content": content}}],
            "usage": {"prompt_tokens": 4, "completion_tokens": 3},
            "mtplx_stats": {
                "session_cache_hit": node_id.endswith("body"),
                "ssd_cache_hit": node_id == "plan",
                "lock_wait_time_s": 0.002,
                "decode_tok_s": 42.5,
                "accepted_by_depth": [3, 2],
                "drafted_by_depth": [4, 4],
                "mtp_depth": 2,
            },
        }

    graph = graph_store.create(_full_graph(workspace.id))
    executor = GraphExecutor(
        graph_store,
        tools,
        memory,
        model_runner=model_runner,
    )
    try:
        run = executor.start(graph.id, inputs={"goal": "build it"})
        approval_tools = []
        while True:
            run = _wait_for(
                graph_store,
                run.id,
                lambda value: value.status in {
                    "waiting_approval",
                    "completed",
                    "failed",
                    "cancelled",
                },
            )
            if run.status != "waiting_approval":
                break
            approval = workspace_store.get_approval(run.pending_approval_id)
            approval_tools.append(approval.tool)
            executor.approve(run.id, approval.id, "approved", resolved_by="test")

        assert run.status == "completed", run.error
        assert run.outputs["plan"] == "I am done"
        assert len(run.outputs["iterations"]) == 2
        assert run.outputs["approved"] is True
        assert (project / "generated.txt").read_text(encoding="utf-8") == (
            "generated by Graph\n"
        )
        assert approval_tools == ["write_file", "run_tests", "graph_human_approval"]
        assert len(calls) == 3
        assert calls[0]["model"] == "mtplx-test-model"
        assert calls[1]["session_id"] == calls[2]["session_id"]
        plan_metrics = run.node_states["plan"]["metrics"]
        assert plan_metrics["model_load_wait_ms"] == 2
        assert plan_metrics["ssd_cache_hit"] is True
        assert plan_metrics["decode_tok_s"] == 42.5
        assert plan_metrics["acceptance_rate"] == pytest.approx(5 / 8)

        events = workspace_store.list_events(run.id, limit=1000)
        kinds = [event.kind for event in events]
        assert kinds.count("loop_iteration_completed") == 2
        assert kinds.count("tool_call") == 2
        assert kinds.count("test_started") == 1
        assert kinds.count("test_completed") == 1
        assert kinds.count("graph_completed") == 1
        assert kinds.count("run_completed") == 1
        assert all(
            approval.status == "consumed"
            for approval in workspace_store.list_approvals(run_id=run.id, limit=20)
        )
    finally:
        executor.close()


def test_loop_pause_checkpoints_and_resume_does_not_repeat_completed_iteration(tmp_path):
    _, _, workspace, graph_store, tools, memory = _stores(
        tmp_path,
        policy={"write": "allow", "terminal": "allow"},
    )
    entered = threading.Event()
    release = threading.Event()
    calls = []

    def model_runner(**kwargs):
        calls.append(kwargs["messages"][0]["content"])
        if len(calls) == 1:
            entered.set()
            assert release.wait(timeout=5)
        return {
            "model": kwargs["model"],
            "choices": [{"message": {"content": f"iteration-{len(calls)}"}}],
        }

    graph = graph_store.create(
        {
            "id": "pause-loop",
            "project_id": workspace.id,
            "workspace_id": workspace.id,
            "name": "Pause Loop",
            "limits": {"max_context_tokens": 8192, "max_steps": 10},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "loop",
                    "type": "loop",
                    "config": {
                        "max_iterations": 3,
                        "body": {
                            "type": "model",
                            "config": {"prompt": "Loop {{loop.index}}"},
                        },
                    },
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "loop"},
                {"source": "loop", "target": "output"},
            ],
        }
    )
    executor = GraphExecutor(graph_store, tools, memory, model_runner=model_runner)
    try:
        run = executor.start(graph.id)
        assert entered.wait(timeout=5)
        executor.pause(run.id)
        release.set()
        paused = _wait_for(graph_store, run.id, lambda value: value.status == "paused")
        assert paused.node_states["loop"]["status"] == "pending"
        assert paused.node_states["loop"]["iterations_completed"] == 1

        executor.resume(run.id)
        completed = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert completed.status == "completed", completed.error
        assert completed.node_states["loop"]["iterations_completed"] == 3
        assert len(calls) == 3
    finally:
        release.set()
        executor.close()


def test_restart_guard_replays_completed_side_effect_without_executing_it_again(tmp_path):
    project, workspace_store, workspace, graph_store, tools, memory = _stores(
        tmp_path,
        policy={"write": "allow"},
    )
    graph = graph_store.create(
        {
            "id": "restart-guard",
            "project_id": workspace.id,
            "workspace_id": workspace.id,
            "name": "Restart Guard",
            "policies": {"write": "allow"},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "write",
                    "type": "tool",
                    "config": {
                        "tool": "write_file",
                        "arguments": {"path": "guarded.txt", "content": "first\n"},
                    },
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "write"},
                {"source": "write", "target": "output"},
            ],
        }
    )
    run = graph_store.create_run(graph)
    execution_key = f"{run.id}:write:attempt:1"
    first = tools.execute(
        workspace.id,
        "write_file",
        {"path": "guarded.txt", "content": "first\n"},
        run_id=run.id,
        idempotency_key=execution_key,
    )
    assert first["ok"] is True
    (project / "guarded.txt").write_text("external change\n", encoding="utf-8")

    states = {key: dict(value) for key, value in run.node_states.items()}
    states["input"].update(
        {"status": "completed", "attempts": 1, "output": {}, "completed_at": "checkpoint"}
    )
    states["write"].update(
        {
            "status": "running",
            "attempts": 1,
            "idempotency_key": execution_key,
            "started_at": "before-restart",
        }
    )
    graph_store.update_run(
        run.id,
        status="running",
        current_node_id="write",
        node_states=states,
    )

    executor = GraphExecutor(graph_store, tools, memory, model_runner=lambda **_: {})
    try:
        recovered = graph_store.get_run(run.id)
        assert recovered.status == "paused"
        assert recovered.node_states["input"]["status"] == "completed"
        assert recovered.node_states["write"]["recovery_guard"] == (
            "interrupted_side_effect"
        )
        with pytest.raises(GraphExecutionError, match="retry_failed_node"):
            executor.resume(run.id)
        with pytest.raises(GraphExecutionError, match="allow_side_effect_retry"):
            executor.retry_failed_node(run.id)

        executor.retry_failed_node(run.id, allow_side_effect_retry=True)
        completed = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert completed.status == "completed", completed.error
        assert completed.node_states["write"]["metrics"]["replayed"] is True
        assert (project / "guarded.txt").read_text(encoding="utf-8") == (
            "external change\n"
        )
        kinds = [event.kind for event in workspace_store.list_events(run.id, limit=1000)]
        assert "graph_recovered" in kinds
    finally:
        executor.close()


def test_memory_curation_uses_one_model_result_across_exact_approval(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    memory.write("shared/source.md", "durable source\n", expected_sha256="")
    memory_path = f"working/project-{workspace.id}/lessons.md"
    calls = []

    def model_runner(**kwargs):
        calls.append(kwargs)
        return {
            "model": kwargs["model"],
            "choices": [{"message": {"content": f"lesson {len(calls)}\n"}}],
        }

    graph = graph_store.create(
        {
            "id": "memory-curation",
            "project_id": workspace.id,
            "workspace_id": workspace.id,
            "name": "Memory Curation",
            "policies": {"memory": "ask"},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "curate",
                    "type": "memory_curate",
                    "config": {
                        "query": "durable",
                        "path": memory_path,
                        "expected_sha256": "",
                    },
                },
                {
                    "id": "output",
                    "type": "output",
                    "config": {"mapping": {"memory": "{{nodes.curate.output.path}}"}},
                },
            ],
            "edges": [
                {"source": "input", "target": "curate"},
                {"source": "curate", "target": "output"},
            ],
        }
    )
    executor = GraphExecutor(graph_store, tools, memory, model_runner=model_runner)
    try:
        run = executor.start(graph.id)
        waiting = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"waiting_approval", "failed"},
        )
        assert waiting.status == "waiting_approval", waiting.error
        assert len(calls) == 1
        approval = workspace_store.get_approval(waiting.pending_approval_id)
        executor.approve(run.id, approval.id, "approved", resolved_by="test")
        completed = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert completed.status == "completed", completed.error
        assert len(calls) == 1
        assert memory.read(memory_path).content == "lesson 1\n"
        assert completed.outputs == {"memory": memory_path}
    finally:
        executor.close()


def test_resource_pressure_pauses_before_execution_and_resumes_cleanly(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    snapshot = _runtime_snapshot(memory_pressure_level=2)
    graph = graph_store.create(
        {
            "id": "resource-pause",
            "project_id": workspace.id,
            "workspace_id": workspace.id,
            "name": "Resource Pause",
            "nodes": [
                {"id": "input", "type": "input"},
                {"id": "output", "type": "output"},
            ],
            "edges": [{"source": "input", "target": "output"}],
        }
    )
    executor = GraphExecutor(
        graph_store,
        tools,
        memory,
        model_runner=lambda **_: {},
        resource_snapshot=lambda: dict(snapshot),
    )
    try:
        run = executor.start(graph.id)
        paused = _wait_for(graph_store, run.id, lambda value: value.status == "paused")
        assert paused.node_states["input"]["status"] == "pending"
        assert "memory pressure" in paused.error
        snapshot["memory_pressure_level"] = 0
        executor.resume(run.id)
        completed = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert completed.status == "completed", completed.error
    finally:
        executor.close()


def test_graph_http_surface_exposes_revisions_controls_events_and_approvals(tmp_path):
    from fastapi.testclient import TestClient
    from test_server_openai import _fake_state

    from mtplx.dreaming import DreamingService
    from mtplx.server.openai import create_app

    project = tmp_path / "project"
    project.mkdir()
    state = _fake_state()
    state.workspace_store = WorkspaceStore(tmp_path / "state")
    state.memory_store = MemoryStore(tmp_path / "memory")
    state.memory_store.initialize()
    state.dreaming_service = DreamingService(state.memory_store)
    state.workspace_tool_service = WorkspaceToolService(
        state.workspace_store,
        sandbox_mode="off",
    )
    state.graph_store = GraphStore(state.workspace_store)
    state.graph_executor = GraphExecutor(
        state.graph_store,
        state.workspace_tool_service,
        state.memory_store,
        model_runner=lambda **_: {},
        resource_snapshot=_runtime_snapshot,
    )

    with TestClient(create_app(state)) as client:
        workspace_response = client.post(
            "/v1/mtplx/workspaces",
            json={"name": "Graph API", "root_path": str(project)},
        )
        assert workspace_response.status_code == 200
        workspace_id = workspace_response.json()["id"]
        payload = {
            "id": "approval-graph",
            "workspace_id": workspace_id,
            "name": "Approval Graph",
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "approve",
                    "type": "human_approval",
                    "config": {"action": "Continue Graph"},
                },
                {
                    "id": "output",
                    "type": "output",
                    "config": {
                        "mapping": {"approved": "{{nodes.approve.output.approved}}"}
                    },
                },
            ],
            "edges": [
                {"source": "input", "target": "approve"},
                {"source": "approve", "target": "output"},
            ],
        }
        validated = client.post("/v1/mtplx/graphs/validate", json=payload)
        assert validated.status_code == 200
        assert validated.json()["valid"] is True
        invalid = client.post(
            "/v1/mtplx/graphs/validate",
            json={**payload, "nodes": []},
        )
        assert invalid.status_code == 422

        created = client.post("/v1/mtplx/graphs", json=payload)
        assert created.status_code == 200
        assert created.json()["revision"] == 1
        updated = client.patch(
            "/v1/mtplx/graphs/approval-graph",
            params={"expected_revision": 1},
            json={"description": "revision two"},
        )
        assert updated.status_code == 200
        assert updated.json()["revision"] == 2
        revisions = client.get(
            "/v1/mtplx/graphs/approval-graph/revisions"
        ).json()["revisions"]
        assert [item["revision"] for item in revisions] == [2, 1]

        started = client.post(
            "/v1/mtplx/graph-runs",
            json={"graph_id": "approval-graph", "inputs": {}},
        )
        assert started.status_code == 200
        run_id = started.json()["id"]
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            run = client.get(f"/v1/mtplx/graph-runs/{run_id}").json()
            if run["status"] == "waiting_approval":
                break
            time.sleep(0.01)
        assert run["status"] == "waiting_approval"
        approvals = client.get(
            f"/v1/mtplx/graph-runs/{run_id}/approvals",
            params={"status": "pending"},
        ).json()["approvals"]
        assert len(approvals) == 1
        approved = client.post(
            f"/v1/mtplx/graph-runs/{run_id}/approve",
            json={
                "approval_id": approvals[0]["id"],
                "decision": "approved",
                "resolved_by": "api-test",
            },
        )
        assert approved.status_code == 200
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            run = client.get(f"/v1/mtplx/graph-runs/{run_id}").json()
            if run["status"] in {"completed", "failed"}:
                break
            time.sleep(0.01)
        assert run["status"] == "completed", run.get("error")
        assert run["outputs"] == {"approved": True}
        events = client.get(f"/v1/mtplx/graph-runs/{run_id}/logs").json()[
            "events"
        ]
        assert any(event["kind"] == "graph_completed" for event in events)
        capabilities = client.get("/v1/mtplx/app/capabilities").json()
        assert capabilities["features"]["graphs"] is True
        assert capabilities["features"]["graph_loop_nodes"] is True


def test_graph_http_runtime_snapshot_separates_selected_and_execution_profiles(
    tmp_path,
):
    from fastapi.testclient import TestClient
    from test_server_openai import _fake_state

    from mtplx.profiles import get_profile
    from mtplx.server.openai import create_app

    project = tmp_path / "project"
    project.mkdir()
    state = _fake_state()
    state.args.profile = "stable"
    state.profile = get_profile("stable")

    with TestClient(create_app(state)) as client:
        workspace = client.post(
            "/v1/mtplx/workspaces",
            json={"name": "Profile telemetry", "root_path": str(project)},
        )
        assert workspace.status_code == 200
        workspace_id = workspace.json()["id"]
        graph = client.post(
            "/v1/mtplx/graphs",
            json={
                "id": "profile-telemetry",
                "workspace_id": workspace_id,
                "name": "Profile telemetry",
                "runtime_requirements": {
                    "provider": "mtplx",
                    "profile": "stable",
                    "require_loaded_model": True,
                },
                "limits": {"max_context_tokens": 4096},
                "nodes": [
                    {"id": "input", "type": "input"},
                    {"id": "output", "type": "output"},
                ],
                "edges": [{"source": "input", "target": "output"}],
            },
        )
        assert graph.status_code == 200
        started = client.post(
            "/v1/mtplx/graph-runs",
            json={"graph_id": "profile-telemetry", "inputs": {}},
        )
        assert started.status_code == 200
        run_id = started.json()["id"]

        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            run = client.get(f"/v1/mtplx/graph-runs/{run_id}").json()
            if run["status"] in {"completed", "failed"}:
                break
            time.sleep(0.01)

        assert run["status"] == "completed", run.get("error")
        snapshot = run["resource_metrics"]["latest_resource_snapshot"]
        assert snapshot["runtime_profile"] == "stable"
        assert snapshot["runtime_execution_profile"] == (
            "long_response_exact_staged"
        )
        events = client.get(
            f"/v1/mtplx/graph-runs/{run_id}/events"
        ).json()["events"]
        snapshots = [
            event["payload"]
            for event in events
            if event["kind"] == "graph_resource_snapshot"
        ]
        assert snapshots
        assert all(item["runtime_profile"] == "stable" for item in snapshots)
        assert all(
            item["runtime_execution_profile"] == "long_response_exact_staged"
            for item in snapshots
        )


def test_output_contract_and_last_output_follow_execution_not_definition_order(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "schema_version": 1,
            "id": "ordered-output",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Ordered output",
            "outputs": {
                "result": {"type": "string", "pattern": "^second$"},
            },
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "second",
                    "type": "model",
                    "config": {"prompt": "after {{last_output}}"},
                },
                {
                    "id": "first",
                    "type": "model",
                    "config": {"prompt": "first"},
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "first"},
                {"source": "first", "target": "second"},
                {"source": "second", "target": "output"},
            ],
        }
    )

    def model_runner(**kwargs):
        return {
            "model": kwargs["model"],
            "choices": [{"message": {"content": kwargs["node_id"]}}],
        }

    executor = GraphExecutor(graph_store, tools, memory, model_runner=model_runner)
    try:
        run = executor.start(graph.id)
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert run.status == "completed", run.error
        assert run.outputs == {"result": "second"}
        assert run.resource_metrics["last_completed_node_id"] == "output"

        bad = graph_store.update(
            graph.id,
            {"outputs": {"answer": {"type": "string"}}},
            expected_revision=1,
        )
        failed = executor.start(bad.id, revision=bad.revision)
        failed = _wait_for(
            graph_store,
            failed.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert failed.status == "failed"
        assert "outputs.answer is required" in failed.error
        assert failed.node_states["output"]["status"] == "failed"
        events = workspace_store.list_events(failed.id, limit=500)
        assert any(event.kind == "graph_output_contract_failed" for event in events)
        assert not any(
            event.kind == "graph_node_completed"
            and event.payload.get("node_id") == "output"
            for event in events
        )
        assert not any(event.kind == "graph_completed" for event in events)
    finally:
        executor.close()


def test_loop_memory_write_uses_exact_graph_level_approval(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(
        tmp_path,
        policy={"read": "allow", "write": "allow", "terminal": "allow"},
    )
    memory_path = f"working/project-{workspace.id}/loop.md"
    graph = graph_store.create(
        {
            "schema_version": 1,
            "id": "loop-memory",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Loop memory",
            "policies": {"memory": "allow"},
            "approval_requirements": {"required_node_ids": ["loop"]},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "loop",
                    "type": "loop",
                    "config": {
                        "max_iterations": 1,
                        "body": {
                            "type": "memory_write",
                            "config": {
                                "path": memory_path,
                                "content": "iteration {{loop.index}}",
                                "expected_sha256": "",
                            },
                        },
                    },
                },
                {
                    "id": "output",
                    "type": "output",
                    "config": {"mapping": {"written": True}},
                },
            ],
            "edges": [
                {"source": "input", "target": "loop"},
                {"source": "loop", "target": "output"},
            ],
        }
    )
    executor = GraphExecutor(graph_store, tools, memory)
    try:
        run = executor.start(graph.id)
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status == "waiting_approval",
        )
        approval = workspace_store.get_approval(run.pending_approval_id)
        assert approval.tool == "memory_write"
        assert approval.arguments["path"] == memory_path
        executor.approve(run.id, approval.id, "approved", resolved_by="test")
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert run.status == "completed", run.error
        assert run.node_states["loop"]["iterations_completed"] == 1
        assert memory.read(memory_path).content == "iteration 0"
        resolved = workspace_store.get_approval(approval.id)
        assert resolved.status == "consumed"
        assert resolved.consumed_at is not None
    finally:
        executor.close()


def test_runtime_requirements_are_enforced_and_resource_snapshot_is_checkpointed(tmp_path):
    _, _, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "schema_version": 1,
            "id": "runtime-contract",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Runtime contract",
            "runtime_requirements": {
                "provider": "mtplx",
                "backend": "mlx",
                "profile": "stable",
                "required_capabilities": ["tool_calls"],
                "require_loaded_model": True,
            },
            "nodes": [
                {"id": "input", "type": "input"},
                {"id": "output", "type": "output"},
            ],
            "edges": [{"source": "input", "target": "output"}],
        }
    )
    executor = GraphExecutor(
        graph_store,
        tools,
        memory,
        resource_snapshot=lambda: {
            "provider": "mtplx",
            "runtime_loaded": True,
            "backend_id": "gguf",
            "loaded_model": "mtplx-test-model",
            "runtime_capabilities": [],
            "memory_pressure_level": 0,
            "thermal_throttled": False,
            "active_memory_bytes": 0,
            "context_window": 65_536,
            "runtime_profile": "stable",
        },
    )
    try:
        run = executor.start(graph.id, start=False)
        assert run.runtime_profile == "stable"
        executor.resume(run.id)
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status == "failed",
        )
        assert "does not satisfy required backend mlx" in run.error
        snapshot = run.resource_metrics["latest_resource_snapshot"]
        assert snapshot["backend_id"] == "gguf"
        assert run.resource_metrics["active_started_at"] is None
    finally:
        executor.close()


def test_cancel_interrupts_active_terminal_process_and_records_evidence(tmp_path):
    project, workspace_store, workspace, graph_store, tools, memory = _stores(
        tmp_path,
        policy={"terminal": "allow", "network": "deny"},
    )
    graph = graph_store.create(
        {
            "schema_version": 1,
            "id": "cancel-command",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Cancel command",
            "policies": {"terminal": "allow", "network": "deny"},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "command",
                    "type": "tool",
                    "timeout_seconds": 30,
                    "config": {
                        "tool": "run_command",
                        "arguments": {
                            "command": "sleep 10; printf late > cancelled.txt",
                            "network": False,
                        },
                    },
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "command"},
                {"source": "command", "target": "output"},
            ],
        }
    )
    executor = GraphExecutor(graph_store, tools, memory)
    try:
        run = executor.start(graph.id)
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            events = workspace_store.list_events(run.id, limit=500)
            if any(event.kind == "tool_call" for event in events):
                break
            time.sleep(0.01)
        else:
            raise AssertionError("terminal tool did not start")
        started = time.monotonic()
        cancelled = executor.cancel(run.id)
        assert cancelled.status == "cancelled"
        deadline = time.monotonic() + 3
        cancelled_result = None
        while time.monotonic() < deadline:
            events = workspace_store.list_events(run.id, limit=500)
            cancelled_result = next(
                (
                    event
                    for event in events
                    if event.kind == "tool_result"
                    and event.payload.get("result", {}).get("cancelled")
                ),
                None,
            )
            if cancelled_result is not None:
                break
            time.sleep(0.01)
        assert cancelled_result is not None
        assert time.monotonic() - started < 3
        assert not (project / "cancelled.txt").exists()
        assert graph_store.get_run(run.id).status == "cancelled"
    finally:
        executor.close()


def test_graph_timeout_counts_active_execution_not_human_approval_wait(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "schema_version": 1,
            "id": "active-timeout",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Active timeout",
            "timeout_seconds": 1,
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "approval",
                    "type": "human_approval",
                    "config": {"action": "Continue after a deliberate wait"},
                },
                {
                    "id": "output",
                    "type": "output",
                    "config": {"mapping": {"approved": True}},
                },
            ],
            "edges": [
                {"source": "input", "target": "approval"},
                {"source": "approval", "target": "output"},
            ],
        }
    )
    executor = GraphExecutor(graph_store, tools, memory)
    try:
        run = executor.start(graph.id)
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status == "waiting_approval",
        )
        approval = workspace_store.get_approval(run.pending_approval_id)
        time.sleep(1.2)
        executor.approve(run.id, approval.id, "approved", resolved_by="test")
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert run.status == "completed", run.error
        assert run.resource_metrics["active_elapsed_seconds"] < 1
        assert run.resource_metrics["active_started_at"] is None
    finally:
        executor.close()


def test_model_node_timeout_is_enforced_even_when_runner_ignores_timeout(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "schema_version": 1,
            "id": "model-timeout",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Model timeout",
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "model",
                    "type": "model",
                    "timeout_seconds": 1,
                    "config": {"prompt": "wait"},
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "model"},
                {"source": "model", "target": "output"},
            ],
        }
    )

    def slow_model(**_kwargs):
        time.sleep(1.5)
        return {"choices": [{"message": {"content": "late"}}]}

    executor = GraphExecutor(graph_store, tools, memory, model_runner=slow_model)
    try:
        started = time.monotonic()
        run = executor.start(graph.id)
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status == "failed",
        )
        assert "model node timeout exceeded" in run.error
        assert time.monotonic() - started < 1.4
        events = workspace_store.list_events(run.id, limit=500)
        assert any(event.kind == "graph_model_timed_out" for event in events)
    finally:
        executor.close()


def test_runtime_telemetry_absence_and_probe_errors_fail_closed(tmp_path):
    _, _, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "id": "runtime-telemetry-fail-closed",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Runtime telemetry fail closed",
            "nodes": [
                {"id": "input", "type": "input"},
                {"id": "output", "type": "output"},
            ],
            "edges": [{"source": "input", "target": "output"}],
        }
    )

    def broken_snapshot():
        raise RuntimeError("probe unavailable")

    cases = [
        ({}, "runtime telemetry is missing provider"),
        (broken_snapshot, "runtime telemetry failed: RuntimeError: probe unavailable"),
    ]
    for snapshot, expected in cases:
        provider = snapshot if callable(snapshot) else lambda value=snapshot: value
        executor = GraphExecutor(
            graph_store,
            tools,
            memory,
            resource_snapshot=provider,
        )
        try:
            run = executor.start(graph.id)
            run = _wait_for(
                graph_store,
                run.id,
                lambda value: value.status == "failed",
            )
            assert expected in run.error
            assert "latest_resource_snapshot" in run.resource_metrics
        finally:
            executor.close()


def test_model_nodes_require_loaded_runtime_and_bind_served_model_and_profile(tmp_path):
    _, _, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "id": "bound-model-runtime",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Bound model runtime",
            "runtime_requirements": {
                "model": "mtplx-test-model",
                "profile": "stable",
                "allow_model_fallback": False,
            },
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "model",
                    "type": "model",
                    "config": {"prompt": "verify runtime"},
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "model"},
                {"source": "model", "target": "output"},
            ],
        }
    )
    calls = []

    def wrong_model(**kwargs):
        calls.append(kwargs)
        return {
            "model": "different-model",
            "choices": [{"message": {"content": "wrong runtime"}}],
        }

    executor = GraphExecutor(
        graph_store,
        tools,
        memory,
        model_runner=wrong_model,
        resource_snapshot=lambda: _runtime_snapshot(
            runtime_profile="stable",
        ),
    )
    try:
        run = executor.start(graph.id)
        run = _wait_for(graph_store, run.id, lambda value: value.status == "failed")
        assert "served model different-model, required mtplx-test-model" in run.error
        assert len(calls) == 1
    finally:
        executor.close()

    profile_executor = GraphExecutor(
        graph_store,
        tools,
        memory,
        model_runner=wrong_model,
        resource_snapshot=lambda: _runtime_snapshot(runtime_profile="fast"),
    )
    try:
        before = len(calls)
        run = profile_executor.start(graph.id)
        run = _wait_for(graph_store, run.id, lambda value: value.status == "failed")
        assert "profile fast does not satisfy required profile stable" in run.error
        assert len(calls) == before
    finally:
        profile_executor.close()

    missing_loaded = _runtime_snapshot(runtime_profile="stable")
    missing_loaded.pop("runtime_loaded")
    missing_executor = GraphExecutor(
        graph_store,
        tools,
        memory,
        model_runner=wrong_model,
        resource_snapshot=lambda: missing_loaded,
    )
    try:
        before = len(calls)
        run = missing_executor.start(graph.id)
        run = _wait_for(graph_store, run.id, lambda value: value.status == "failed")
        assert "runtime telemetry is missing runtime_loaded" in run.error
        assert len(calls) == before
    finally:
        missing_executor.close()


def test_loop_body_retry_until_and_step_accounting_are_enforced(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "id": "loop-retry-until",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Loop retry until",
            "runtime_requirements": {"allow_model_fallback": False},
            "limits": {"max_steps": 8, "max_context_tokens": 8192},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "loop",
                    "type": "loop",
                    "config": {
                        "max_iterations": 5,
                        "until": {"path": "loop.output", "equals": "stop"},
                        "body": {
                            "type": "model",
                            "retry": {"max_attempts": 2, "backoff_seconds": 0},
                            "config": {"prompt": "attempt {{loop.index}}"},
                        },
                    },
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "loop"},
                {"source": "loop", "target": "output"},
            ],
        }
    )
    calls = []

    def flaky_model(**kwargs):
        calls.append(kwargs)
        if len(calls) == 1:
            raise RuntimeError("transient model failure")
        return {
            "model": kwargs["model"],
            "choices": [{"message": {"content": "stop"}}],
        }

    executor = GraphExecutor(
        graph_store,
        tools,
        memory,
        model_runner=flaky_model,
        resource_snapshot=_runtime_snapshot,
    )
    try:
        run = executor.start(graph.id)
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert run.status == "completed", run.error
        assert len(calls) == 2
        assert run.node_states["loop"]["iterations_completed"] == 1
        assert run.node_states["loop"]["iteration_metrics"][0]["attempts"] == 2
        assert run.node_states["loop"]["output"] == ["stop"]
        assert run.resource_metrics["loop_body_steps_completed"] == 1
        assert run.resource_metrics["steps_completed"] == 3
        events = workspace_store.list_events(run.id, limit=500)
        assert any(event.kind == "loop_body_retry_scheduled" for event in events)
    finally:
        executor.close()


def test_loop_rechecks_resources_between_iterations_and_resumes_from_checkpoint(tmp_path):
    _, _, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "id": "loop-resource-checkpoints",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Loop resource checkpoints",
            "limits": {"max_steps": 10, "max_context_tokens": 8192},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "loop",
                    "type": "loop",
                    "config": {
                        "max_iterations": 3,
                        "body": {
                            "type": "model",
                            "config": {"prompt": "iteration {{loop.index}}"},
                        },
                    },
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "loop"},
                {"source": "loop", "target": "output"},
            ],
        }
    )
    calls = []
    probe = {"count": 0, "pause": True}

    def snapshot():
        probe["count"] += 1
        pressure = 2 if probe["pause"] and probe["count"] >= 4 else 0
        return _runtime_snapshot(memory_pressure_level=pressure)

    def model_runner(**kwargs):
        calls.append(kwargs)
        return {
            "model": kwargs["model"],
            "choices": [{"message": {"content": f"value-{len(calls)}"}}],
        }

    executor = GraphExecutor(
        graph_store,
        tools,
        memory,
        model_runner=model_runner,
        resource_snapshot=snapshot,
    )
    try:
        run = executor.start(graph.id)
        run = _wait_for(graph_store, run.id, lambda value: value.status == "paused")
        assert "memory pressure" in run.error
        assert run.node_states["loop"]["iterations_completed"] == 1
        assert len(calls) == 1

        probe["pause"] = False
        executor.resume(run.id)
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert run.status == "completed", run.error
        assert run.node_states["loop"]["iterations_completed"] == 3
        assert len(calls) == 3
        assert run.resource_metrics["steps_completed"] == 5
    finally:
        executor.close()


def test_loop_timeout_bounds_the_whole_loop_not_each_iteration(tmp_path):
    _, _, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "id": "whole-loop-timeout",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Whole Loop timeout",
            "limits": {"max_steps": 10, "max_context_tokens": 8192},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "loop",
                    "type": "loop",
                    "timeout_seconds": 1,
                    "config": {
                        "max_iterations": 3,
                        "body": {
                            "type": "model",
                            "config": {"prompt": "slow {{loop.index}}"},
                        },
                    },
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "loop"},
                {"source": "loop", "target": "output"},
            ],
        }
    )
    calls = []

    def slow_model(**kwargs):
        calls.append(kwargs)
        time.sleep(0.6)
        return {
            "model": kwargs["model"],
            "choices": [{"message": {"content": "slow"}}],
        }

    executor = GraphExecutor(graph_store, tools, memory, model_runner=slow_model)
    try:
        run = executor.start(graph.id)
        run = _wait_for(graph_store, run.id, lambda value: value.status == "failed")
        assert "Loop node timeout exceeded: 1 seconds" in run.error
        assert 1 <= len(calls) <= 2
        assert run.node_states["loop"]["iterations_completed"] < 3
    finally:
        executor.close()


def test_model_cancellation_releases_the_lane_for_the_next_graph(tmp_path):
    _, _, workspace, graph_store, tools, memory = _stores(tmp_path)

    def create_model_graph(identifier, prompt):
        return graph_store.create(
            {
                "id": identifier,
                "workspace_id": workspace.id,
                "project_id": workspace.id,
                "name": identifier,
                "nodes": [
                    {"id": "input", "type": "input"},
                    {
                        "id": "model",
                        "type": "model",
                        "timeout_seconds": 10,
                        "config": {"prompt": prompt},
                    },
                    {"id": "output", "type": "output"},
                ],
                "edges": [
                    {"source": "input", "target": "model"},
                    {"source": "model", "target": "output"},
                ],
            }
        )

    blocked_graph = create_model_graph("cancel-aware-model", "block")
    quick_graph = create_model_graph("next-model", "quick")
    entered = threading.Event()
    stopped = threading.Event()

    def model_runner(**kwargs):
        prompt = kwargs["messages"][0]["content"]
        if prompt == "block":
            entered.set()
            while not kwargs["cancellation_event"].wait(0.01):
                pass
            stopped.set()
            raise RuntimeError("cancelled")
        return {
            "model": kwargs["model"],
            "choices": [{"message": {"content": "quick"}}],
        }

    executor = GraphExecutor(graph_store, tools, memory, model_runner=model_runner)
    try:
        blocked = executor.start(blocked_graph.id)
        assert entered.wait(timeout=5)
        assert executor.cancel(blocked.id).status == "cancelled"

        started = time.monotonic()
        quick = executor.start(quick_graph.id)
        quick = _wait_for(
            graph_store,
            quick.id,
            lambda value: value.status in {"completed", "failed"},
            timeout=3,
        )
        assert quick.status == "completed", quick.error
        assert stopped.wait(timeout=1)
        assert time.monotonic() - started < 2
        assert graph_store.get_run(blocked.id).status == "cancelled"
    finally:
        executor.close()


def test_graph_run_pins_workspace_root_across_workspace_updates(tmp_path):
    project, workspace_store, workspace, graph_store, tools, memory = _stores(
        tmp_path,
        policy={"write": "allow"},
    )
    other = tmp_path / "other-project"
    other.mkdir()
    graph = graph_store.create(
        {
            "id": "pinned-workspace-root",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Pinned workspace root",
            "policies": {"write": "allow"},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "write",
                    "type": "tool",
                    "config": {
                        "tool": "write_file",
                        "arguments": {"path": "pinned.txt", "content": "original\n"},
                    },
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "write"},
                {"source": "write", "target": "output"},
            ],
        }
    )
    executor = GraphExecutor(graph_store, tools, memory)
    try:
        run = executor.start(graph.id, start=False)
        assert run.workspace_root == str(project)
        workspace_store.update_workspace(workspace.id, root_path=str(other))
        executor.resume(run.id)
        run = _wait_for(
            graph_store,
            run.id,
            lambda value: value.status in {"completed", "failed"},
        )
        assert run.status == "completed", run.error
        assert (project / "pinned.txt").read_text(encoding="utf-8") == "original\n"
        assert not (other / "pinned.txt").exists()
    finally:
        executor.close()


def test_graph_memory_rejects_cross_project_write_before_requesting_approval(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "id": "memory-project-boundary",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Memory project boundary",
            "policies": {"memory": "ask"},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "memory",
                    "type": "memory_write",
                    "config": {
                        "path": "shared/forbidden.md",
                        "content": "must not write",
                        "expected_sha256": "",
                    },
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "memory"},
                {"source": "memory", "target": "output"},
            ],
        }
    )
    executor = GraphExecutor(graph_store, tools, memory)
    try:
        run = executor.start(graph.id)
        run = _wait_for(graph_store, run.id, lambda value: value.status == "failed")
        assert "write access denied for shared/forbidden.md" in run.error
        assert workspace_store.list_approvals(run_id=run.id, limit=20) == []
    finally:
        executor.close()


def test_recovery_fails_runs_with_missing_or_hash_invalid_pinned_graphs(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)

    def create_graph(identifier):
        return graph_store.create(
            {
                "id": identifier,
                "workspace_id": workspace.id,
                "project_id": workspace.id,
                "name": identifier,
                "nodes": [
                    {"id": "input", "type": "input"},
                    {"id": "output", "type": "output"},
                ],
                "edges": [{"source": "input", "target": "output"}],
            }
        )

    missing_graph = create_graph("missing-pinned-graph")
    missing_run = graph_store.create_run(missing_graph)
    graph_store._revision_path(missing_graph.id, missing_graph.revision).unlink()

    invalid_graph = create_graph("invalid-pinned-graph")
    invalid_run = graph_store.create_run(invalid_graph)
    invalid_path = graph_store._revision_path(invalid_graph.id, invalid_graph.revision)
    invalid_payload = json.loads(invalid_path.read_text(encoding="utf-8"))
    invalid_payload["name"] = "tampered"
    invalid_path.write_text(json.dumps(invalid_payload), encoding="utf-8")

    executor = GraphExecutor(graph_store, tools, memory)
    try:
        for run_id in (missing_run.id, invalid_run.id):
            run = graph_store.get_run(run_id)
            assert run.status == "failed"
            assert "cannot recover pinned Graph revision" in run.error
            assert workspace_store.get_run(run_id).status == "failed"
            events = workspace_store.list_events(run_id, limit=100)
            assert any(event.kind == "graph_recovery_failed" for event in events)
    finally:
        executor.close()


def test_approval_denial_and_cancellation_clear_durable_approval_state(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "id": "approval-terminal-states",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Approval terminal states",
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "approval",
                    "type": "human_approval",
                    "config": {"action": "Continue"},
                },
                {"id": "output", "type": "output"},
            ],
            "edges": [
                {"source": "input", "target": "approval"},
                {"source": "approval", "target": "output"},
            ],
        }
    )
    executor = GraphExecutor(graph_store, tools, memory)
    try:
        denied = executor.start(graph.id)
        denied = _wait_for(
            graph_store,
            denied.id,
            lambda value: value.status == "waiting_approval",
        )
        denied_approval = workspace_store.get_approval(denied.pending_approval_id)
        denied = executor.approve(
            denied.id,
            denied_approval.id,
            "denied",
            resolved_by="test",
        )
        assert denied.status == "failed"
        assert denied.pending_approval_id is None
        assert denied.node_states["approval"]["status"] == "failed"
        assert denied.node_states["approval"]["pending_approval_id"] is None
        assert workspace_store.get_approval(denied_approval.id).status == "denied"

        cancelled = executor.start(graph.id)
        cancelled = _wait_for(
            graph_store,
            cancelled.id,
            lambda value: value.status == "waiting_approval",
        )
        cancelled_approval = workspace_store.get_approval(
            cancelled.pending_approval_id
        )
        cancelled = executor.cancel(cancelled.id)
        assert cancelled.status == "cancelled"
        assert cancelled.pending_approval_id is None
        assert cancelled.node_states["approval"]["status"] == "cancelled"
        assert workspace_store.get_approval(cancelled_approval.id).status == "denied"
        with pytest.raises(GraphExecutionError, match="cannot resolve approval"):
            executor.approve(
                cancelled.id,
                cancelled_approval.id,
                "approved",
            )
        with pytest.raises(WorkspaceConflictError, match="terminal graph run is immutable"):
            graph_store.update_run(cancelled.id, error="contradictory terminal state")
    finally:
        executor.close()


def test_restart_commits_prepared_completion_without_duplicate_events(tmp_path):
    _, workspace_store, workspace, graph_store, tools, memory = _stores(tmp_path)
    graph = graph_store.create(
        {
            "id": "prepared-completion-recovery",
            "workspace_id": workspace.id,
            "project_id": workspace.id,
            "name": "Prepared completion recovery",
            "outputs": {"result": {"type": "string"}},
            "nodes": [
                {"id": "input", "type": "input"},
                {
                    "id": "output",
                    "type": "output",
                    "config": {"mapping": {"result": "done"}},
                },
            ],
            "edges": [{"source": "input", "target": "output"}],
        }
    )
    run = graph_store.create_run(graph)
    states = {key: dict(value) for key, value in run.node_states.items()}
    states["input"].update(
        {"status": "completed", "output": {}, "completed_at": "checkpoint"}
    )
    states["output"].update(
        {
            "status": "completed",
            "attempts": 1,
            "output": {"result": "done"},
            "completed_at": "checkpoint",
        }
    )
    prepared = graph_store.update_run(
        run.id,
        status="running",
        outputs={"result": "done"},
        node_states=states,
        current_node_id="output",
        resource_metrics={
            "steps_completed": 2,
            "completion_prepared": True,
            "completion_prepared_at": "checkpoint",
        },
    )
    workspace_store.append_event(
        prepared.id,
        "graph_node_completed",
        {"node_id": "output", "node_type": "output", "attempt": 1},
    )
    workspace_store.append_event(
        prepared.id,
        "graph_completed",
        {
            "graph_id": graph.id,
            "graph_revision": graph.revision,
            "outputs": {"result": "done"},
        },
    )

    executor = GraphExecutor(graph_store, tools, memory)
    try:
        recovered = graph_store.get_run(prepared.id)
        assert recovered.status == "completed"
        assert recovered.outputs == {"result": "done"}
        assert recovered.resource_metrics["completion_committed_at"]
        assert "completion_prepared" not in recovered.resource_metrics
        kinds = [
            event.kind
            for event in workspace_store.list_events(prepared.id, limit=500)
        ]
        assert kinds.count("graph_node_completed") == 1
        assert kinds.count("graph_completed") == 1
        assert kinds.count("run_completed") == 1
    finally:
        executor.close()
