"""Full-stack parity regression test for the DeepSeek-V4 MLX forward.

This is the test that was MISSING: the M2 component gates passed at ~1e-7 each, yet
the assembled 43-layer forward was wrong (the attention never integrated the
compressor's compressed KV, so 41/43 layers attended only the sliding window and
real inference produced repetitive garbage). This test composes the WHOLE forward
and pins it against a golden reference.

The golden fixture (tests/fixtures/deepseek_v4_parity_golden.npz) was captured from
the authoritative reference (deepseek-ai/DeepSeek-V4-Flash/inference/model.py, run on
CPU with pure-torch stubs for the CUDA/tilelang kernels) at a shrunk config that
exercises every layer type: window+hash, ratio-4 (overlap compressor + indexer)+hash,
ratio-128 (non-overlap compressor)+hash, ratio-4+score, window+score. Generated by
scratchpad/gen_golden.py; the reference forward was validated layer-by-layer against
the MLX model before capture (max_rel ~1.8e-6, argmax 160/160).

Runs on the CPU device so MLX fp32 matmul is bit-exact (its GPU fast path carries
~7.5e-4 relative, unrelated to correctness). No torch, no download.
"""
import importlib.util
import os
import sys

import numpy as np
import pytest

pytest.importorskip("mlx.core")
import mlx.core as mx  # noqa: E402

@pytest.fixture(autouse=True)
def _cpu_default_device():
    # CPU-pinned by design, but the pin must stay test-scoped: a module-level
    # set_default_device leaks into every later-collected module (pytest
    # imports all test modules before running any) and flips the engine's
    # Metal bit-exactness suites onto CPU fallbacks process-wide.
    previous = mx.default_device()
    mx.set_default_device(mx.cpu)
    try:
        yield
    finally:
        mx.set_default_device(previous)

_HERE = os.path.dirname(os.path.abspath(__file__))
_FIXTURE = os.path.join(_HERE, "fixtures", "deepseek_v4_parity_golden.npz")
_MODEL = os.path.join(_HERE, "..", "mtplx", "models", "deepseek_v4.py")
_spec = importlib.util.spec_from_file_location("dsv4_parity_undertest", _MODEL)
D = importlib.util.module_from_spec(_spec)
sys.modules["dsv4_parity_undertest"] = D
_spec.loader.exec_module(D)


def _build():
    g = np.load(_FIXTURE)
    (vocab, dim, nl, nhash, nh, hd, rd, ql, ol, og, mi, nre, nae, seq) = [int(v) for v in g["cfg"]]
    cr = [int(c) for c in g["compress_ratios"]]
    args = D.ModelArgs(
        vocab_size=vocab, hidden_size=dim, num_hidden_layers=nl, num_hash_layers=nhash,
        num_attention_heads=nh, head_dim=hd, qk_rope_head_dim=rd, q_lora_rank=ql,
        o_lora_rank=ol, o_groups=og, moe_intermediate_size=mi, n_routed_experts=nre,
        num_experts_per_tok=nae, index_n_heads=nh, index_head_dim=hd, index_topk=512,
        compress_ratios=cr, compress_rope_theta=160000.0, sliding_window=128,
        rope_scaling={"original_max_position_embeddings": 65536, "factor": 16,
                      "beta_fast": 32, "beta_slow": 1, "type": "yarn"},
        scoring_func="sqrtsoftplus", routed_scaling_factor=1.5, swiglu_limit=0.0,
    )
    model = D.Model(args)
    weights = []
    for k in g.files:
        if k.startswith("w::"):
            arr = g[k]
            weights.append((k[3:], mx.array(arr.astype(np.int32) if "tid2eid" in k else arr)))
    model.load_weights(weights)
    ids = mx.array(g["input_ids"])
    return g, args, model, ids


def test_full_stack_logits_match_reference():
    g, args, model, ids = _build()
    logits = model(ids)
    mx.eval(logits)
    got = np.array(logits.astype(mx.float32))
    ref = g["ref_logits"]
    mad = float(np.max(np.abs(got - ref)))
    rel = mad / (float(np.max(np.abs(ref))) + 1e-12)
    assert mad < 1e-3, f"logits diverge: max_abs={mad:.3e} max_rel={rel:.3e}"
    # argmax agreement is the acceptance bar David set ("logits match ref")
    am_got = np.array(mx.argmax(logits[0], axis=-1))
    am_ref = ref[0].argmax(-1)
    assert np.array_equal(am_got, am_ref), (
        f"argmax disagrees at {int((am_got != am_ref).sum())}/{len(am_ref)} positions")


def test_per_layer_block_parity():
    """Layer-by-layer guard so a future regression localizes, not just the logits."""
    g, args, model, ids = _build()
    ref_blocks = g["ref_blocks"]  # [NL, 1, SEQ, hc, DIM]
    h = model.model.embed_tokens(ids)
    h = mx.broadcast_to(h[:, :, None, :], (*h.shape[:2], args.hc_mult, h.shape[-1]))
    worst = 0.0
    for i, layer in enumerate(model.model.layers):
        h = layer(h, mask=None, cache=None, input_ids=ids)
        mx.eval(h)
        d = float(np.max(np.abs(np.array(h.astype(mx.float32)) - ref_blocks[i])))
        worst = max(worst, d)
        assert d < 1e-3, f"layer {i} (ratio={args.compress_ratios[i]}) block diverges max_abs={d:.3e}"
    assert worst < 1e-3
