#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  curl -fsSL https://raw.githubusercontent.com/youssofal/MTPLX/main/scripts/install_macos.sh | bash

Installs MTPLX from PyPI into ~/.mtplx/venv and creates a durable `mtplx`
launcher in ~/.local/bin. On Apple Silicon Homebrew installs, it also writes
/opt/homebrew/bin/mtplx when that directory is writable.

Environment:
  MTPLX_PACKAGE_SPEC=mtplx              Package spec to install, for example mtplx==0.1.4
  MTPLX_PYTHON=/path/to/python3         Python interpreter override
  MTPLX_VENV=~/.mtplx/venv              Install venv path
  MTPLX_USER_BIN=~/.local/bin           User launcher directory
  MTPLX_GLOBAL_BIN=/opt/homebrew/bin    Optional global launcher directory
  MTPLX_SKIP_GLOBAL_LAUNCHER=1          Do not copy into Homebrew/global bin
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

if [ "$(uname -s)" != "Darwin" ] || [ "$(uname -m)" != "arm64" ]; then
  echo "error: this installer is for Apple Silicon Macs." >&2
  echo "MTPLX depends on MLX and is not a Windows/Linux/Intel Mac package." >&2
  exit 2
fi

package_spec="${MTPLX_PACKAGE_SPEC:-mtplx}"
venv="${MTPLX_VENV:-$HOME/.mtplx/venv}"
user_bin="${MTPLX_USER_BIN:-$HOME/.local/bin}"
launcher="$user_bin/mtplx"
python_bin="${MTPLX_PYTHON:-}"

if [ -z "$python_bin" ]; then
  candidates=(
    /opt/homebrew/bin/python3.14
    /opt/homebrew/bin/python3.13
    /opt/homebrew/bin/python3.12
    /opt/homebrew/bin/python3.11
    /opt/homebrew/bin/python3
    /usr/local/bin/python3.14
    /usr/local/bin/python3.13
    /usr/local/bin/python3.12
    /usr/local/bin/python3.11
    /usr/local/bin/python3
    python3.14
    python3.13
    python3.12
    python3.11
    python3
  )
  for candidate in "${candidates[@]}"; do
    if [ -x "$candidate" ]; then
      python_bin="$candidate"
      break
    elif command -v "$candidate" >/dev/null 2>&1; then
      python_bin="$(command -v "$candidate")"
      break
    fi
  done
fi

if [ -z "$python_bin" ]; then
  echo "error: could not find Python 3.11+." >&2
  echo "Checked Homebrew paths (/opt/homebrew/bin, /usr/local/bin) and PATH." >&2
  echo "Install Python 3.11+ first, then rerun this installer." >&2
  exit 2
fi

"$python_bin" - <<'PY'
import sys

if sys.version_info < (3, 11):
    print(
        f"error: MTPLX needs Python 3.11+, found {sys.version.split()[0]}",
        file=sys.stderr,
    )
    raise SystemExit(2)
PY

echo "Using Python: $python_bin"
echo "Installing:   $package_spec"
echo "Venv:         $venv"

"$python_bin" -m venv "$venv"
"$venv/bin/python" -m pip install -U pip
"$venv/bin/python" -m pip install -U "$package_spec"

mkdir -p "$user_bin"
cat > "$launcher" <<EOF
#!/usr/bin/env bash
# MTPLX launcher. Generated by scripts/install_macos.sh.
set -e

if [ -z "\${HF_HOME:-}" ] && [ -d "\$HOME/.cache/huggingface-mtplx" ]; then
  export HF_HOME="\$HOME/.cache/huggingface-mtplx"
fi

exec "$venv/bin/mtplx" "\$@"
EOF
chmod 755 "$launcher"

path_snippet="
# MTPLX CLI
case \":\$PATH:\" in
  *\":$user_bin:\"*) ;;
  *) export PATH=\"$user_bin:\$PATH\" ;;
esac
"

for rcfile in "$HOME/.zprofile" "$HOME/.zshrc" "$HOME/.bash_profile"; do
  touch "$rcfile"
  if ! grep -q 'MTPLX CLI' "$rcfile"; then
    printf '%s\n' "$path_snippet" >> "$rcfile"
  fi
done

global_launcher=""
if [ "${MTPLX_SKIP_GLOBAL_LAUNCHER:-0}" != "1" ]; then
  if [ -n "${MTPLX_GLOBAL_BIN:-}" ]; then
    global_bin="$MTPLX_GLOBAL_BIN"
  elif [ -d /opt/homebrew/bin ]; then
    global_bin="/opt/homebrew/bin"
  elif [ -d /usr/local/bin ]; then
    global_bin="/usr/local/bin"
  else
    global_bin=""
  fi

  if [ -n "$global_bin" ]; then
    if cp "$launcher" "$global_bin/mtplx" 2>/dev/null && chmod 755 "$global_bin/mtplx" 2>/dev/null; then
      global_launcher="$global_bin/mtplx"
    else
      echo "Note: could not write to $global_bin (permission denied). Skipping global launcher."
      echo "      You can rerun with sudo or set MTPLX_SKIP_GLOBAL_LAUNCHER=1 to silence this."
    fi
  fi
fi

"$launcher" --version
"$launcher" help >/dev/null

echo
echo "MTPLX installed:"
echo "  $launcher"
if [ -n "$global_launcher" ]; then
  echo "  $global_launcher"
fi
echo
echo "Open a new Terminal tab, or run:"
echo "  export PATH=\"$user_bin:\$PATH\""
echo
echo "Then start MTPLX:"
echo "  mtplx start"
